src/Wiki/WikiMaireBundle/Form/Type/ProjetType.php
<?php

namespace Wiki\WikiMaireBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ProjetType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomprojet', 'text',array('label' => 'Nom du Projet'))
            ->add('description', 'textarea',array('label' => 'Description'))
            ->add('daterealisation','date', array('label' => 'Année de Réalisation'))
            ->add('duree','text', array('label' => 'Durée'))
            ->add('gains', 'text' , array('label' => 'Gains pour la commune'))
            ->add('cout', 'number',array('label' => 'Coût de  la Réalisation'))
            ->add('file', 'file', array('label' => 'Photo du projet', 'required' => false))
            ->add('x', 'hidden')
            ->add('y', 'hidden')
            ->add('w', 'hidden')
            ->add('h', 'hidden')
            ->add('financement', null, array("label" => "Financement", "required" => false)

            );
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Wiki\WikiMaireBundle\Form\Model\ProjetModel'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'wiki_wikimairebundle_projet';
    }
}

src/Wiki/WikiMaireBundle/Controller/DefaultController.php
<?php

namespace Wiki\WikiMaireBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{

    public function indexAction()
    {
        return $this->render('WikiWikiMaireBundle:Default:index.html.twig');
    }

    public function contactAction()
    {
        return $this->render('WikiWikiMaireBundle:Default:contact.html.twig');
    }

    public function homeAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('WikiWikiMaireBundle:Projet')->findAll();

        return $this->render('WikiWikiMaireBundle:Default:home.html.twig', array(
            'entities' => $entities,
        ));
    }

}

src/Wiki/WikiMaireBundle/Resources/views/Default/contact.html.twig
{% extends '::base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="css/modern-business.css">
    <link rel="stylesheet" href="{{ asset('bundles/wikiwikimaire/css/contact.css') }}" type="text/css"/>
{% endblock %}

{% block body -%}


    {% for flashMessage in app.session.flashbag.get('notice') %}
        <div class="flash-notice">
            {{ flashMessage }}
        </div>
    {% endfor %}
    <a class="button-Retour" a href="{{ path('wiki_wiki_maire_homepage') }}"><h1>Retour</h1></a>
    <div class="rectangle">
    <h2>Nous Contacter</h2>
        </div>
    <form action="{{ path('contact') }}" method="post" {{ form_enctype(form) }} class="inscription">
        {{ form_errors(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.telephone) }}
        {{ form_row(form.mail) }}
        {{ form_row(form.message) }}

        {{ form_rest(form) }}

        <input type="submit" value="Envoyer"/>
    </form>


{% endblock %}

src/Wiki/WikiMaireBundle/Resources/views/Default/home.html.twig
{% block stylesheets %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="{{ asset('bundles/wikiwikimaire/css/home.css') }}" type="text/css"/>

    <!-- Optional theme -->
    <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
{% endblock %}

{% block body -%}

    <!-- Infos de connection -->
    <div class="container info_co">
        <div class="col-md-8"></div>
        <div class="col-md-4">
            <ul>
                <li>Commune de {{ app.user.commune.nomcommune }}</li>
                <li><a href="{{ path('fos_user_profile_show')}}">Mon Profil <span class="glyphicon glyphicon-user"></span></a></li>
                <li><a href="{{ path('fos_user_security_logout') }}">Se déconnecter <span class="glyphicon glyphicon-log-out"></span></a></li>
            </ul>
        </div>
    </div>

    <!-- Corps de la Page -->
    <div class="container corps_page">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <ul id="hiden">
                <li>
                    <a href="{{ path('projet_create') }}">
                        <button class="btn-default1"><h2>Proposer un Projet</h2></button>
                    </a>
                </li><br>
                <li>
                <a href=""><!-- A compléter avec la route vers les Experts -->
                        <button class="btn-default2"><h2>Trouver un Expert</h2></button>
                    </a>
                </li>
            </ul>
            <!-- Barre de Recherche de Projet -->
            <div id="imaginary_container">
                <div id="recherche">
                    <button class="btn-default3"><h3>Rechercher un Projet</h3></button>
                    </div>
                    <div class="rectangle">
                </div>
                <div class="input-group stylish-input-group">
                    <input type="text" class="form-control quicksearch" placeholder="Entrez votre recherche" id="cache">
                    <span class="input-group-addon">
                        <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

    <!--<button id="cache">Fait disparaitre</button>-->

    <!-- Projets Recherchés -->
    <div class="grid projet_hide">
        <div class="projects">
            {% for entity in entities %}
                <div class="row project element-item col-md-11">
                    {% if loop.index is even %}
                        <div class="col-md-5">
                            <a href="#">
                                <img src="{{ app.request.basepath }}/uploads/{{ entity.photo }}" class="img-thumbnail">
                            </a>
                        </div>
                        <div class="col-md-7">
                            <p>Description :</p>

                            <p>{{ entity.description }}</p>
                        </div>
                    {% else %}
                        <div class="col-md-7">
                            <p>Description :</p>

                            <p>{{ entity.description }}</p>
                        </div>
                        <div class="col-md-5">
                            <a href="#">
                                <img src="{{ app.request.basepath }}/uploads/{{ entity.photo }}" class="img-thumbnail">
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <!-- jQuery -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        $(function()
        {
            $('.projet_hide').hide();
            $('#cache').keyup(function() {
                $('#hiden').hide(1000);
                $('.projet_hide').show(1000);
            });
        });
    </script>
    <script>
        $(function () {
            // quick search regex
            var qsRegex;
            // init Isotope
            var $grid = $('.grid').isotope({
                itemSelector: '.element-item',
                layoutMode: 'fitRows',
                filter: function () {
                    return qsRegex ? $(this).text().match(qsRegex) : true;
                }
            });
            // use value of search field to filter
            var $quicksearch = $('.quicksearch').keyup(debounce(function () {
                qsRegex = new RegExp($quicksearch.val(), 'gi');
                $grid.isotope();
            }, 200));
        });
        // debounce so filtering doesn't happen every millisecond
        function debounce(fn, threshold) {
            var timeout;
            return function debounced() {
                if (timeout) {
                    clearTimeout(timeout);
                }
                function delayed() {
                    fn();
                    timeout = null;
                }

                timeout = setTimeout(delayed, threshold || 100);
            }
        }
    </script>
{% endblock %}

src/Wiki/WikiMaireBundle/Resources/views/Default/index.html.twig
{% extends "::base.html.twig" %}

{% block title %} Accueil - {{ parent() }} {% endblock %}

{% block body %}

    <a href="{{ path('homepage_afterlogin') }}">
        <button class="btn btn-default">Connexion</button>
    </a>

    <div id="my_carousel" class="carousel slide" data-ride="carousel">
        <!-- Bulles -->
        <ol class="carousel-indicators">
            <li data-target="#my_carousel" data-slide-to="0" class="active"></li>
            <li data-target="#my_carousel" data-slide-to="1"></li>
            <li data-target="#my_carousel" data-slide-to="2"></li>
        </ol>
        <!-- Slides -->
        <div class="carousel-inner">
            <!-- Page 1 -->
            <div class="item active slider">
                <div class="carousel-page">
                    <img src="{{ asset('bundles/wikiwikimaire/img/slide/slide1.jpg') }}" class="img-responsive" style="margin:0px auto;">
                </div>
                <div class=" slide_bg" >Projet de Réhabilitation d'un vieux Gymnase</div>
            </div>

            <!-- Page 2 -->
            <div class="item slider">
                <div class="carousel-page">
                    <img src="{{ asset('bundles/wikiwikimaire/img/slide/slide2.jpg') }}" class="img-responsive img-rounded" style="margin:0px auto;">

                </div>
                <div class="slide_bg">Projet de Réhabilitation de conduite d'eau potable</div>
            </div>

            <!-- Page 3 -->
            <div class="item slider">
                <div class="carousel-page">
                    <img src="{{ asset('bundles/wikiwikimaire/img/slide/slide3.jpeg') }}" class="img-responsive img-rounded" style="margin:0px auto;max-height:100%;">

                </div>
                <div class="slide_bg">Projet de construction d'une école numérique</div>
            </div>
        </div>
        <!-- Contrôles -->
        <a class="left carousel-control" href="#my_carousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#my_carousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-offset-1">
                <div id="column" class="left">
                    <div class="on-third-left">
                        <h4>Comment ça marche ?</h4>

                        <div class="blockquote">
                            <p class="blockquote"> Vous avez un nouveau projet ?
                                Vous ne savez pas comment vous lancer ? Un projet similaire existe t il ? Une fois
                                inscrit sur le site, vous pourrez identifier des projets proches du votre, contacter le
                                maire qui a réalisé celui ci et avoir des réponses claires à vos questions...</p>
                        </div>
                        <div class="blockquote">
                            <p class="blockquote"> Vous recherchez un expert pour vous aider dans la réalisation de
                                votre projet .
                                Ce site peut vous apporter des réponses, vous allez pouvoir sélectionner et contac-
                                ter des experts avec des compétences juridiques, techniques, financières, pédago-
                                giques....dans les domaines de votre recherche.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a href="{{ path('contact') }}">
            <button class="btn1 btn-default">Inscription</button>
        </a>

    </div>



    <!--
    // Proposition de projets


    <div class="hr_line"></div>
    <div class="section"  style="padding-bottom: 25px;">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h3 class="text-center">Projet 1</h3>
                    <img src="{{ asset('bundles/wikiwikimaire/img/img_test.jpg') }}" alt="" class="img-thumbnail img-responsive">
                    <p style="padding-top: 10px;">Laboratoire de recyclage et de fabrication numérique.Les fablabs sont un réseau mondial de laboratoires locaux...</p>
                    <a href="#" class="btn btn-default">Lire plus</a>
                </div>
                <div class="col-md-3">
                    <h3 class="text-center">Projet 2</h3>
                    <img src="{{ asset('bundles/wikiwikimaire/img/img_test.jpg') }}" alt="" class="img-thumbnail img-responsive">
                    <p style="padding-top: 10px;">Projet d’innovation des Femmes dans le domaine des TIC. Le groupe femmes & TIC RIM a eu comme activité.</p>
                    <a href="#" class="btn btn-default">Lire plus</a>
                </div>
                <div class="col-md-3">
                    <h3 class="text-center">Projet 3</h3>
                    <img src="{{ asset('bundles/wikiwikimaire/img/img_test.jpg') }}" alt="" class="img-thumbnail img-responsive">
                    <p style="padding-top: 10px;">Projet d’innovation dans la cartographie numérique libre.OSM est un projet qui a pour but de constituer une base de données géographique...</p>
                    <a href="#" class="btn btn-default">Lire plus</a>
                </div>
                <div class="col-md-3">
                    <h3 class="text-center">Projet 4</h3>
                    <img src="{{ asset('bundles/wikiwikimaire/img/img_test.jpg') }}" alt="" class="img-thumbnail img-responsive">
                    <p style="padding-top: 10px;">Projet d’innovation dans le développement des applications mobile. projet de Mauritanie Mobile consiste à encourager les jeunes à innover...</p>
                    <a href="#" class="btn btn-default">Lire plus</a>
                </div>
            </div>
        </div>
    </div>

    -->
    <footer>
        <p>&copy; Wiki des Maires</p>
    </footer>
{% endblock %}